export const DOM = {
    menuScreen: document.getElementById('menu-screen'),
    quizScreen: document.getElementById('quiz-screen'),
    resultScreen: document.getElementById('result-screen'),
    reviewScreen: document.getElementById('review-screen'),
    quizList: document.getElementById('quiz-list'),
    breadcrumb: document.getElementById('breadcrumb'),
    breadcrumbHome: document.getElementById('breadcrumb-home'),
    breadcrumbMode: document.getElementById('breadcrumb-mode'),
    breadcrumbQuizSep: document.getElementById('breadcrumb-quiz-sep'),
    breadcrumbQuiz: document.getElementById('breadcrumb-quiz'),
    quizTitle: document.getElementById('quiz-title'),
    progressBar: document.getElementById('progress-bar'),
    questionCounter: document.getElementById('question-counter'),
    liveScore: document.getElementById('live-score'),
    difficultyBadge: document.getElementById('difficulty-badge'),
    questionContainer: document.getElementById('question-container'),
    questionText: document.getElementById('question-text'),
    optionsContainer: document.getElementById('options-container'),
    feedbackContainer: document.getElementById('feedback-container'),
    feedbackTitle: document.getElementById('feedback-title'),
    feedbackExplanation: document.getElementById('feedback-explanation'),
    nextBtn: document.getElementById('next-btn'),
    finalScore: document.getElementById('final-score'),
    resultIcon: document.getElementById('result-icon'),
    resultMessage: document.getElementById('result-message'),
    returnHomeBtn: document.getElementById('return-home-btn'),
    tryAgainBtn: document.getElementById('try-again-btn'),
    reviewBtn: document.getElementById('review-btn'),
    reviewBackBtn: document.getElementById('review-back-btn'),
    reviewList: document.getElementById('review-list'),
    shareBtn: document.getElementById('share-btn'),
    modeBtns: document.querySelectorAll('.mode-btn'),
    searchInput: document.getElementById('search-input'),
    resumeToast: document.getElementById('resume-toast'),
    resumeToastText: document.getElementById('resume-toast-text'),
    resumeDismiss: document.getElementById('resume-dismiss'),
    timerToggle: document.getElementById('timer-toggle'),
    timerBarContainer: document.getElementById('timer-bar-container'),
    timerBar: document.getElementById('timer-bar'),
    timerCount: document.getElementById('timer-count'),
    countModal: document.getElementById('count-modal'),
    countBtns: document.querySelectorAll('.count-btn'),
    countCancel: document.getElementById('count-cancel'),
    confettiCanvas: document.getElementById('confetti-canvas'),
};

export const state = {
    quizzes: [],
    currentQuizData: null,
    currentQuestionIndex: 0,
    score: 0,
    hasAnsweredCurrent: false,
    currentMode: 'general',
    currentFile: null,
    answeredLog: [],
    allMixQuestions: null,
    pendingQuizCallback: null,
    timerEnabled: false,
    timerInterval: null,
    timerRemaining: 0,
    toastTimer: null,
};

export const TIMER_SECONDS = 30;
export const SCORES_KEY = 'quiz_scores_v2';
export const SESSION_KEY = 'quiz_progress';
export const MODE_LABELS = {
    general: 'General Quiz',
    bible: 'Bible Mastery',
    topics: 'Topics Mastery',
    memory: 'Memory Verses',
    mix: 'Mix Mode',
};
